<?php defined('SYSPATH') or die('No direct script access.');

return array(
	'ace' => array(
		'modes' => array(
			'Common' => array(
				'php' => 'PHP',
				'html' => 'HTML',
				'css' => 'CSS',
				'javascript' => 'JavaScript',
				'coffee' => 'CoffeeScript',
				'less' => 'LESS',
				'sass' => 'SASS',
				'python' => 'Python',
				'text' => 'Text'
			),
			'Others' => array(
				'abap' => 'ABAP',
				'asciidoc' => 'AsciiDoc',
				'c9search' => 'C9Search',
				'coldfusion' => 'ColdFusion',
				'csharp' => 'C#',
				'curly' => 'Curly',
				'dart' => 'Dart',
				'diff' => 'Diff',
				'dot' => 'Dot',
				'ftl' => 'FreeMarker',
				'glsl' => 'Glsl',
				'golang' => 'Go',
				'groovy' => 'Groovy',
				'haxe' => 'haXe',
				'haml' => 'HAML',
				'c_cpp' => 'C/C++',
				'clojure' => 'Clojure',
				'jade' => 'Jade',
				'java' => 'Java',
				'jsp' => 'JSP',
				'json' => 'JSON',
				'jsx' => 'JSX',
				'latex' => 'LaTeX',
				'lisp' => 'Lisp',
				'scheme' => 'Scheme',
				'liquid' => 'Liquid',
				'livescript' => 'LiveScript',
				'logiql' => 'LogiQL',
				'lua' => 'Lua',
				'luapage' => 'LuaPage',
				'lucene' => 'Lucene',
				'lsl' => 'LSL',
				'makefile' => 'Makefile',
				'markdown' => 'Markdown',
				'objectivec' => 'Objective-C',
				'ocaml' => 'OCaml',
				'pascal' => 'Pascal',
				'perl' => 'Perl',
				'pgsql' => 'pgSQL',
				'powershell' => 'Powershell',
				'r' => 'R',
				'rdoc' => 'RDoc',
				'rhtml' => 'RHTML',
				'ruby' => 'Ruby',
				'scad' => 'OpenSCAD',
				'scala' => 'Scala',
				'scss' => 'SCSS',
				'sh' => 'SH',
				'sql' => 'SQL',
				'stylus' => 'Stylus',
				'svg' => 'SVG',
				'tcl' => 'Tcl',
				'tex' => 'Tex',
				'textile' => 'Textile',
				'tm_snippet' => 'tmSnippet',
				'toml' => 'toml',
				'typescript' => 'Typescript',
				'vbscript' => 'VBScript',
				'xml' => 'XML',
				'xquery' => 'XQuery',
				'yaml' => 'YAML'
			)
		),
		'ext' => array(
			'js'  => 'javascript',
			'py'  => 'python',
			'cpp' => 'c_cpp',
			'md'  => 'markdown',
			'm'   => 'objectivec'
		),
		'themes' => array(
			'Bright' => array(
				'chrome' => 'Chrome',
				'clouds' => 'Clouds',
				'crimson_editor' => 'Crimson Editor',
				'dawn' => 'Dawn',
				'dreamweaver' => 'Dreamweaver',
				'eclipse' => 'Eclipse',
				'github' => 'GitHub',
				'solarized_light' => 'Solarized Light',
				'textmate' => 'TextMate',
				'tomorrow' => 'Tomorrow',
				'xcode' => 'XCode'
			),
			'Dark' => array(
				'ambiance' => 'Ambiance',
				'chaos' => 'Chaos',
				'clouds_midnight' => 'Clouds Midnight',
				'cobalt' => 'Cobalt',
				'idle_fingers' => 'idleFingers',
				'kr_theme' => 'krTheme',
				'merbivore' => 'Merbivore',
				'merbivore_soft' => 'Merbivore Soft',
				'mono_industrial' => 'Mono Industrial',
				'monokai' => 'Monokai',
				'pastel_on_dark' => 'Pastel on dark',
				'solarized_dark' => 'Solarized Dark',
				'twilight' => 'Twilight',
				'tomorrow_night' => 'Tomorrow Night',
				'tomorrow_night_blue' => 'Tomorrow Night Blue',
				'tomorrow_night_bright' => 'Tomorrow Night Bright',
				'tomorrow_night_eighties' => 'Tomorrow Night 80s',
				'vibrant_ink' => 'Vibrant Ink'
			)
		)
	)
);